### ISSUE TITLE
Official grammars repository

### ISSUE THREAD

**Issue by KvanTTT** [lextm/restructuredtext-antlr#1]
Would you like to upload grammar to the official grammars repository https://github.com/antlr/grammars-v4?

**Comment by lextm** [comment]
Good suggestion. The current grammar (version 0.9) is still far from perfect, and still needs a lot of tuning.

I will upload the 1.0 release when everything gets better to the official repository.

**Comment by lextm** [comment]
Good suggestion. I will do it now.

**Comment by lextm** [comment]
Closed via https://github.com/antlr/grammars-v4/pull/1028
